### ISSUE TITLE
Iteration Plan v1.3.5 - May 2021

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmcv#1026]
MMCV v1.3.4 has been released, see the plan in https://github.com/open-mmlab/mmcv/issues/998 and the [release notes](https://github.com/open-mmlab/mmcv/releases/tag/v1.3.4)
We list our plan for v1.3.5, which will be released at the end of May (around 24th May).
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

Features:

- [ ] Enable exporting to onnx for PointRend #953
- [x] Add neptune.ai logger hook #1025
- [x] Supports CUDA ops of BorderAlign module #1021
- [x] Add truncated normal weight initialization #935
- [x] Add ms_deformable_attn in parrots #1042

Enhancements:
- [ ] Add Windows CI #1023
- [ ] Support resume for fp16 training #1013
- [ ] Refactor the baseclass releated to transformer #978

Fixes:
- [x] Fix the bug where logs are missing when two or more loggers were set #1015

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.
