### ISSUE TITLE
Iteration Plan v1.3.6 - June 2021

### ISSUE THREAD

**Issue by zhouzaida** [open-mmlab/mmcv#1053]
MMCV v1.3.5 has been released, see the plan in https://github.com/open-mmlab/mmcv/issues/1026 and the [release notes](https://github.com/open-mmlab/mmcv/releases/tag/v1.3.5)
We list our plan for v1.3.6, which will be released on June 12th.
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

Features:

- [x] Enable exporting to onnx for PointRend #953
- [ ] Porting mmcv for hip #1022
- [ ] Support LR_ReduceOnPlateau #1033
- [x] Add DvcliveLoggerHook #1075

Enhancements:
- [ ] Add Windows CI #1023
- [x] Support resume for fp16 training #1013
- [ ] Refactor the baseclass releated to transformer #978
- [x] Imporve windows support for list_from_file #1043
- [ ] Use more cpus in building #1046
- [ ] Decreasing the cycle amplitude after each period in cyclic lr #783

Fixes:
- [x] Fix MMCls ckpts links #1067

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.

**Comment by hokmund** [comment]
I created a [PR](https://github.com/open-mmlab/mmcv/pull/1059) for [this issue](https://github.com/open-mmlab/mmcv/issues/783).
Could you please include it to the next release?

**Comment by zhouzaida** [comment]
> I created a [PR](https://github.com/open-mmlab/mmcv/pull/1059) for [this issue](https://github.com/open-mmlab/mmcv/issues/783).
> Could you please include it to the next release?

OK, thanks for your contribution.

**Comment by Quebradawill** [comment]
When can mmcv-full support Python 3.9?

**Comment by ZwwWayne** [comment]
> When can mmcv-full support Python 3.9?

We have not tested it yet, but theoretically, if python 3.9 does not bring many BC-breakings mmcv should work well with python 3.9. We are planning to provide pre-built wheels for python 3.9 in the future if we have enough resources.
