### ISSUE TITLE
Iteration Plan v1.3.7 - June 2021

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmcv#1098]
MMCV v1.3.6 has been released, see the [plan](https://github.com/open-mmlab/mmcv/issues/1053) and the [release notes](https://github.com/open-mmlab/mmcv/releases/tag/v1.3.6)
We list our plan for v1.3.7, which will be released on June 26th.
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

Features:

- [ ] Porting mmcv for hip #1022
- [ ] Support LR_ReduceOnPlateau #1033
- [ ] Support variables in base files for configs #1083

Enhancements:
- [ ] Add Windows CI #1023
- [ ] Use more cpus in building #1046
- [ ] Decreasing the cycle amplitude after each period in cyclic lr #783
- [ ] Support image reading while ignoring EXIF orientation info #1091
- [ ] Optimize the PyTorch CUDA implementation for Criss Cross Attention #1088

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.

**Comment by yeliudev** [comment]
Hi @ZwwWayne! May I ask that will the `ConvModule` inherit from `BaseModule` in the newer version of mmcv? Currently, the `ConvModule` may not be properly initialized using `init_cfg`.

```python
class Net(BaseModule):

    def __init__(self, init_cfg=dict(type='Constant', layer='Conv2d', val=0)):
        super(Net, self).__init__(init_cfg)
        self.conv_module = ConvModule(128, 128, 3)
```

In this case, `self.conv_module` will be finally initialized by its own method (Kaiming) but not Constant since ConvModule can not determine whether itself has been initialized using `self._is_init`.

**Comment by zhouzaida** [comment]
> Hi @ZwwWayne! May I ask that will the `ConvModule` inherit from `BaseModule` in the newer version of mmcv? Currently, the `ConvModule` may not be properly initialized using `init_cfg`.
> 
> ```python
> class Net(BaseModule):
> 
>     def __init__(self, init_cfg=dict(type='Constant', layer='Conv2d', val=0)):
>         super(Net, self).__init__(init_cfg)
>         self.conv_module = ConvModule(128, 128, 3)
> ```
> 
> In this case, `self.conv_module` will be finally initialized by its own method (kaiming normal) but not constant since ConvModule can not determine whether itself has been initialized using `self._is_init`.

@MeowZheng

**Comment by MeowZheng** [comment]
Many thanks for you reporting this issue. It is a little difficult, as the inner parts have higher priority, but we will solve it asap.
