### ISSUE TITLE
Iteration Plan v1.3.8 - June 2021

### ISSUE THREAD

**Issue by zhouzaida** [open-mmlab/mmcv#1119]
MMCV v1.3.7 has been released, see the [release notes](https://github.com/open-mmlab/mmcv/releases/tag/v1.3.7)
We list our plan for v1.3.8, which will be released on June 26th.
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

Features:

- [ ] Porting mmcv for hip #1022
- [ ] Support LR_ReduceOnPlateau #1033
- [x] Support variables in base files for configs #1083

Enhancements:

- [ ] Add Windows CI #1023
- [ ] Use more cpus in building #1046
- [ ] Decreasing the cycle amplitude after each period in cyclic lr #783
- [x] Support image reading while ignoring EXIF orientation info #1091
- [x] Optimize the PyTorch CUDA implementation for Criss Cross Attention #1088
- [ ] Refactor docs #1102
- [x] EvalHook uses case-insensitive key indicator matching and configurabl ...#1076

Fixes:

- [x] Fix the permission denied error on windows. #1077
- [ ] Fix SyncBN build in PyTorch 1.9 #1138
- [ ] Change dict update order #1108

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.
