### ISSUE TITLE
Progress of Chinese Documentation

### ISSUE THREAD

**Issue by zhouzaida** [open-mmlab/mmcv#1175]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] docs_zh_CN/get_started/build.md (@zhouzaida, #1353)
- [x] docs_zh_CN/get_started/installation.md 
- [x] docs_zh_CN/get_started/introduction.md 
- [x] docs_zh_CN/deployment/onnx.md (@grimoire, #1331)
- [x] docs_zh_CN/deployment/onnxruntime_custom_ops.md (@grimoire #1331)
- [x] docs_zh_CN/deployment/onnxruntime_op.md (@grimoire #1331)
- [x] docs_zh_CN/deployment/tensorrt_custom_ops.md  (@grimoire #1336)
- [x] docs_zh_CN/deployment/tensorrt_plugin.md (@grimoire #1336)
- [x] docs_zh_CN/understand_mmcv/cnn.md(@bofen97, #1246)
- [x] docs_zh_CN/understand_mmcv/config.md (@AluminiumOxide, #1204)
- [x] docs_zh_CN/understand_mmcv/ops.md (@zhouzaida, #1349)
- [x] docs_zh_CN/understand_mmcv/registry.md (@AluminiumOxide, #1204)
- [x] docs_zh_CN/understand_mmcv/runner.md (@hhaAndroid, #1202 )
- [x] docs_zh_CN/understand_mmcv/utils.md(@jiang1997, #1232)
- [x] docs_zh_CN/understand_mmcv/visualization.md (@zhouzaida, #1350)
- [x] docs_zh_CN/faq.md(@EricKani, #1251)
- [x] docs_zh-CN/community/contributing.md (@zhouzaida, #1351)

In addition, we provide a [document](https://github.com/open-mmlab/mmcv/blob/master/TERMINOLOGY.md) that is used as a reference for English-Chinese terminology translation

**Comment by bofen97** [comment]
我想翻译 docs_zh_CN/understand_mmcv/cnn.md 请问接下来应该怎么做呢，还需要我重新提一个issue吗？如果需要的话请问issue标题应该怎么写 谢谢。

**Comment by zhouzaida** [comment]
> 我想翻译 docs_zh_CN/understand_mmcv/cnn.md 请问接下来应该怎么做呢，还需要我重新提一个issue吗？如果需要的话请问issue标题应该怎么写 谢谢。

感谢你的贡献，我会@你的

**Comment by EricKani** [comment]
我翻译docs_zh_CN/faq.md吧 谢谢

**Comment by zhouzaida** [comment]
> 我翻译docs_zh_CN/faq.md吧 谢谢

got it

**Comment by yyz561** [comment]
onnx.md/ onnxruntime_custom_ops.md/ onnxruntime_op.md 这三篇文档如果暂时没人翻译，我可以来。我对这块内容暂时不是很熟悉，所以可能时间上会久一点点
