### ISSUE TITLE
Easy contributions! Add type annotation for mmcv~

### ISSUE THREAD

**Issue by HAOCHENYE** [open-mmlab/mmcv#1948]
Hi guys, we are planning to add type annotation for python code in MMCV. PRs of adding type annotation from community are welcomed :stuck_out_tongue_closed_eyes:. To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to add type annotation for one of the following modules  :rocket::rocket:.

- [x] runner part1
  - [x] [base_runner.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_runner.py)  #2003 
  - [x] [epoch_based_runner.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py)  #2003
  - [x] [iter_based_runner.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/iter_based_runner.py)  #2003
  - [x] [base_module.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_module.py)  #2020
  - [x] [builder.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/builder.py)  @ytzhao  #1985 
  - [x] [checkpoint.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py)  #2020
  - [x] [default_constructor.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/default_constructor.py)  #2020
  - [x] [dist_utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/dist_utils.py)  #2020
  - [x] [fp16_utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/fp16_utils.py)  #2020
  - [x] [log_buffer.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/log_buffer.py)  #2020
  - [x] [priority.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/priority.py)  #2020
  - [x] [utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/utils.py)  #2008
  - [x] [optimizer](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/optimizer)  #2008 

- [x] runner part2
  - [x] [checkpoint.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py)  @triwahyuu  #1991 
  - [x] [closure.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/closure.py) @triwahyuu  #1991 
  - [x] [ema.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/ema.py) @triwahyuu  #1991 
  - [x] [evaluation.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/evaluation.py) @triwahyuu  #1991 
  - [x] [hook.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/hook.py) @triwahyuu  #1991 
  - [x] [iter_timer.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/iter_timer.py) @triwahyuu  #1991 
  - [x] [lr_updater.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py)  @WINDSKY45  #1988
  - [x] [memory.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/memory.py) @triwahyuu  #1991 
  - [x] [momentum_updater.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/momentum_updater.py) @triwahyuu  #1991 
  - [x] [optimizer.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/optimizer.py) @triwahyuu  #1991
  - [x] [sync_buffer.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/sync_buffer.py) @triwahyuu  #1991

- [x] runner part3
  - [x] [logger](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/hooks/logger)  #2000 

- [x] ops part1
  - [x] [active_rotated_filter.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/active_rotated_filter.py)  #2017
  - [x] [assign_score_withk.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/assign_score_withk.py) #2023
  - [x] [ball_query.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/ball_query.py)@ShawnHXH #2037  #1981 
  - [x] [bbox.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/bbox.py)  @RangeKing https://github.com/open-mmlab/mmcv/pull/1981
  - [x] [border_align.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/border_align.py)@ShawnHXH  #2037
  - [x] [box_iou_rotated.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/box_iou_rotated.py)  @RangeKing https://github.com/open-mmlab/mmcv/pull/1981
  - [x] [carafe.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/carafe.py) #2032
  - [x] [cc_attention.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/cc_attention.py)  @zengxiang68  #1987 
  - [x] [contour_expand.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/contour_expand.py)  @zengxiang68  #1987 
  - [x] [convex_iou.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/convex_iou.py)  @zengxiang68  #1987 
  - [x] [corner_pool.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/corner_pool.py)  #2032
  - [x] [correlation.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/correlation.py)@ShawnHXH  #2037 
  - [x] [deform_conv.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/deform_conv.py)@ShawnHXH  #2037 
  - [x] [deform_roi_pool.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/deform_roi_pool.py)@ShawnHXH  #2037 
  - [x] [deprecated_wrappers.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/deprecated_wrappers.py)@ShawnHXH  #2037 
  - [x] [diff_iou_rotated.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/diff_iou_rotated.py)  #2032

- [x] ops part2
  - [x] [focal_loss.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/focal_loss.py)  @WINDSKY45  #1994
  - [x] [furthest_point_sample.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/furthest_point_sample.py)  @WINDSKY45  #1994
  - [x] [fused_bias_leakyrelu.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/fused_bias_leakyrelu.py) #2030
  - [x] [gather_points.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/gather_points.py)#2030
  - [x] [group_points.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/group_points.py)#2030
  - [x] [info.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/info.py)@WINDSKY45  #2030
  - [x] [iou3d.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/iou3d.py)  @gy-7  #1989
  - [x] [knn.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/knn.py)@WINDSKY45  #2030
  - [x] [masked_conv.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/masked_conv.py)@WINDSKY45  #2030
  - [x] [merge_cells.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/merge_cells.py)@WINDSKY45  #2030
  - [x] [min_area_polygons.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/min_area_polygons.py)@WINDSKY45  #2030
  - [x] [modulated_deform_conv.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/modulated_deform_conv.py)@WINDSKY45  #2030
  - [x] [multi_scale_deform_attn.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/multi_scale_deform_attn.py) @WINDSKY45  #2030
  - [x] [nms.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py) @liuyanyi  #2006
  - [x] [pixel_group.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/pixel_group.py)  #2016
  - [x] [point_sample.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/point_sample.py)  #2019
  - [x] [points_in_boxes.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/points_in_boxes.py)  #2007 
  - [x] [points_in_polygons.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/points_in_polygons.py) #2013 
  - [x] [points_sampler.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/points_sampler.py)  #2015 

- [x] ops part3
  - [x] [psa_mask.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/psa_mask.py)  #1995
  - [x] [riroi_align_rotated.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/riroi_align_rotated.py)  #1995
  - [x] [roi_align.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align.py)  #1995
  - [x] [roi_align_rotated.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align_rotated.py)  #1995
  - [x] [roi_pool.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_pool.py)  #1995
  - [x] [roiaware_pool3d.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roiaware_pool3d.py)  #1995
  - [x] [roipoint_pool3d.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roipoint_pool3d.py)  #1995
  - [x] [rotated_feature_align.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/rotated_feature_align.py)  #1995
  - [x] [saconv.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/saconv.py)  #1995
  - [x] [scatter_points.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/scatter_points.py)  #1995
  - [x] [sparse_conv.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sparse_conv.py)  #1995
  - [x] [sparse_functional.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sparse_functional.py)  #1995
  - [x] [sparse_modules.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sparse_modules.py)  #1995
  - [x] [sparse_ops.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sparse_ops.py)  #1995
  - [x] [sparse_pool.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sparse_pool.py)  #1995
  - [x] [sparse_structure.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sparse_structure.py)  #1995
  - [x] [sync_bn.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/sync_bn.py)  #1995
  - [x] [three_interpolate.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/three_interpolate.py)   #1995
  - [x] [three_nn.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/three_nn.py)  #1995
  - [x] [tin_shift.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/tin_shift.py)  #1995
  - [x] [upfirdn2d.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/upfirdn2d.py)  #1995
  - [x] [voxelize.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/voxelize.py)  #1995

- [x] [bricks](https://github.com/open-mmlab/mmcv/tree/master/mmcv/cnn/bricks)  #1993
- [x] [cnn/utils](https://github.com/open-mmlab/mmcv/tree/master/mmcv/cnn/utils)  #1996 
- [ ] net
  - [x] [alexnet.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/alexnet.py)  @yangrisheng  #1983
  - [ ] [builder.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/builder.py)  @triple-Mu  #1980
  - [x] [resnet.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/resnet.py)  #1982 
  - [x] [vgg.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/vgg.py)  @nxznm  #2050 
- [x] [fileio](https://github.com/open-mmlab/mmcv/tree/master/mmcv/fileio)
  - [x] [handlers](https://github.com/open-mmlab/mmcv/tree/master/mmcv/fileio/handlers)  #1997
  - [x] [file_client](https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/file_client.py) #1942
  - [x] [io](https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/file_client.py)  #1997
  - [x] [parse](https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/parse.py)  #1997
- [ ] [utils](https://github.com/open-mmlab/mmcv/tree/master/mmcv/utils)
- [x] [parallel](https://github.com/open-mmlab/mmcv/tree/master/mmcv/parallel)  #2031
- [x] [engine](https://github.com/open-mmlab/mmcv/tree/master/mmcv/engine)  #2034
- [x] [video](https://github.com/open-mmlab/mmcv/tree/master/mmcv/video)
  - [x] [io](https://github.com/open-mmlab/mmcv/blob/master/mmcv/video/io.py)  #1950
  - [x] [optflow](https://github.com/open-mmlab/mmcv/blob/master/mmcv/video/optflow.py)  #1950
  - [x] [processing](https://github.com/open-mmlab/mmcv/blob/master/mmcv/video/processing.py)  #1999
- [x] [visualization](https://github.com/open-mmlab/mmcv/tree/master/mmcv/visualization)
  - [x] [image.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py) #1946
  - [x] [optflow.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/optflow.py) #1947
  - [x] [color.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/color.py) #1947
- [ ] [image](https://github.com/open-mmlab/mmcv/tree/master/mmcv/image)
  - [x] [colorspace.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/colorspace.py)  #1999
  - [ ] [geometric.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/geometric.py)  #2063
  - [ ] [io.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/io.py)  #2063
  - [ ] [misc.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/misc.py)  #2063
  - [x] [photometric.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/photometric.py) #1999
- [x] [tensorrt](https://github.com/open-mmlab/mmcv/tree/master/mmcv/tensorrt)  #1950 
- [x] [onnx](https://github.com/open-mmlab/mmcv/tree/master/mmcv/onnx)  #1999
- [x] [quantization](https://github.com/open-mmlab/mmcv/blob/master/mmcv/arraymisc/quantization.py)  #1950 
- [ ] [device](https://github.com/open-mmlab/mmcv/tree/master/mmcv/device)  #1990

**Comment by ShawnHXH** [comment]
Hi,
thanks for the wonderful work, I am very interested in this community, so I would like to take a part: `net-resnet.py`.

**Comment by RangeKing** [comment]
I added type hints in `ops part1` [bbox.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/bbox.py) and [box_iou_rotated.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/box_iou_rotated.py) in PR https://github.com/open-mmlab/mmcv/pull/1981.

**Comment by yangrisheng** [comment]
Thank you for this wonderful work, I am willing to translate [alexnet.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/alexnet.py)

**Comment by nxznm** [comment]
I am willing to add type hints in [vgg.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/vgg.py).

**Comment by triple-Mu** [comment]
I am willing to add type hints in https://github.com/open-mmlab/mmcv/pull/1980

**Comment by WINDSKY45** [comment]
I am willing to add type hints in [lr_updater.py](https://github.com/openmmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py)

**Comment by HAOCHENYE** [comment]
> I am willing to add type hints in
> 
> [https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/colorspace.py#L127](url)
> 
> .

Hi~ [colorspace.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/colorspace.py) has been picked up by # 1980， would you mind choosing another task?

**Comment by xpo0a** [comment]
issue#1948

**Comment by triwahyuu** [comment]
Hi I'm willing to add type hints in [device](https://github.com/open-mmlab/mmcv/tree/master/mmcv/device) and [cnn/utils](https://github.com/open-mmlab/mmcv/tree/master/mmcv/cnn/utils)

**Comment by gy-7** [comment]
hey, I'm willing to add type hints in [iou3d.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/iou3d.py)

**Comment by zhouzaida** [comment]
> Hi~ [colorspace.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/colorspace.py) has been picked up by #1980， would you mind choosing another task?

Hi @xpo0a , [onnx](https://github.com/open-mmlab/mmcv/tree/master/mmcv/onnx) has been picked up by https://github.com/open-mmlab/mmcv/pull/1980, would you mind choosing another module?

**Comment by zhouzaida** [comment]
> Hi @xpo0a , [onnx](https://github.com/open-mmlab/mmcv/tree/master/mmcv/onnx) has been picked up by #1980, would you mind choosing another module?

Hi @triwahyuu, `device` and `cnn/utils` have been picked up by other contributors, would you mind choosing another module?

**Comment by triwahyuu** [comment]
I think I could take all of the runner part2 except for the one already taken @zhouzaida

**Comment by zhouzaida** [comment]
> 

Okay

**Comment by zhouzaida** [comment]
> I think I could take all of the runner part2 except for the one already taken @zhouzaida

Okay

**Comment by WINDSKY45** [comment]
I'm willing to add type hints in [focal_loss.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/focal_loss.py)

**Comment by liuyanyi** [comment]
I added hints for [nms.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py) in #2006, plaese have a check.

**Comment by ThiriKid** [comment]
issue#1948

**Comment by WINDSKY45** [comment]
I'm willing to add type hints in [utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/utils.py) and [optimizer](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/optimizer)

**Comment by zhouzaida** [comment]
> I added hints for [nms.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py) in #2006, plaese have a check.

Okay, thanks for your contribution.

**Comment by ShawnHXH** [comment]
> Hi, thanks for the wonderful work, I am very interested in this community, so I would like to take a part: `net-resnet.py`.

Hi, I am still willing to take the rest part of `ops part1`.

**Comment by zhouzaida** [comment]
> > Hi, thanks for the wonderful work, I am very interested in this community, so I would like to take a part: `net-resnet.py`.
> 
> Hi, I am still willing to take the rest part of `ops part1`.

Okay, thanks for your contributions.

**Comment by WINDSKY45** [comment]
> I'm willing to add type hints in [utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/utils.py) and [optimizer](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/optimizer)

 Hi, I am also willing to add type hints in the rest of `runner part1` and `ops part2`.

**Comment by zhouzaida** [comment]
> > I'm willing to add type hints in [utils.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/utils.py) and [optimizer](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/optimizer)
> 
> Hi, I am also willing to add type hints in the rest of `runner part1` and `ops part2`.

Okay, thanks for your contributions.

**Comment by triwahyuu** [comment]
Hi @zhouzaida, I think I could do [`logger`](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/hooks/logger) as well

**Comment by zhouzaida** [comment]
> Hi @zhouzaida, I think I could do [`logger`](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/hooks/logger) as well

Hi, thanks for your contributions, but `logger` will be resolved by #2000.

**Comment by tcexeexe** [comment]
I'm willing to add type hints in [engine](https://github.com/open-mmlab/mmcv/tree/master/mmcv/engine)

**Comment by zhouzaida** [comment]
> Hello! I have added type hints in [engine](https://github.com/open-mmlab/mmcv/tree/master/mmcv/engine) in #2025 , please have a check

Okay. Thanks for your contributions.

**Comment by tcexeexe** [comment]
> > Hello! I have added type hints in [engine](https://github.com/open-mmlab/mmcv/tree/master/mmcv/engine) in #2025 , please have a check
> 
> Okay. Thanks for your contributions.

@zhouzaida 
Hello, Thanks for your suggestion!
l have change the PR in #2034

**Comment by triple-Mu** [comment]
I have pr in https://github.com/open-mmlab/mmcv/pull/2063
