### ISSUE TITLE
Iteration Plan v1.3.4 - May 2021

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmcv#998]
MMCV v1.3.2 and v1.3.3 have been released. 
We list our plan for v1.3.4, which will be released in the middle of May.
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

Features:

- [x] Support triangular CyclicLrUpdator (#1001)
- [x] Add test util for checking stand-alone python scripts (#1007)
- [x] Add step momentum updater to support MMDet3D (#1011)
- [x] Add pixel group operators that will be used in [MMOCR](https://github.com/open-mmlab/mmocr) (#993)
- [ ] ~Enable exporting to onnx for PointRend (#953)~
- [x] Fix encoding issue in windows environment (#983)
- [x] Support corner_pool related custom operators for onnxruntime in mmcv (#997  )
- [x] Support custom operators cummax and cummin for onnxruntime #1010
- [x] Support saving and loading  `hook_msgs` in checkpoint (#962)

Enhancements:
- [x] Set priority of default hooks in runner #970
- [x] Update weight initialization in cnn.md #912 

Fixes:
- [x] Fix DCN fp16 #1014
- [x] Fix the bug of iteration number in val flow https://github.com/open-mmlab/mmcv/pull/914

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.

**Comment by v-qjqs** [comment]
Hi, `mmcv::CornerPool` custom operator for onnxruntime is supported [here.](https://github.com/open-mmlab/mmcv/pull/997)

**Comment by fcakyon** [comment]
@ZwwWayne it would be great if neptune.ai logger hook would be added in the next release: https://github.com/open-mmlab/mmcv/pull/1017

**Comment by ZwwWayne** [comment]
> @ZwwWayne it would be great if neptune.ai logger hook would be added in the next release: #1025

OK, let's try to make it in the next release.
